apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"mongo-express"},"name":"mongo-express","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mongo-express"}},"template":{"metadata":{"labels":{"app":"mongo-express"}},"spec":{"containers":[{"env":[{"name":"ME_CONFIG_MONGODB_ADMINUSERNAME","valueFrom":{"secretKeyRef":{"key":"mongo-root-username","name":"mongodb-secret"}}},{"name":"ME_CONFIG_MONGODB_ADMINPASSWORD","valueFrom":{"secretKeyRef":{"key":"mongo-root-password","name":"mongodb-secret"}}},{"name":"ME_CONFIG_MONGODB_SERVER","valueFrom":{"configMapKeyRef":{"key":"database_url","name":"mongodb-configmap"}}}],"image":"mongo-express","name":"mongo-express","ports":[{"containerPort":8081}]}]}}}}
  creationTimestamp: "2024-12-11T16:07:47Z"
  generation: 1
  labels:
    app: mongo-express
  name: mongo-express
  namespace: default
  resourceVersion: "16383"
  uid: 480a0c1a-9471-4dec-99e8-40f574421712
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mongo-express
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo-express
    spec:
      containers:
      - env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              key: mongo-root-username
              name: mongodb-secret
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              key: mongo-root-password
              name: mongodb-secret
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              key: database_url
              name: mongodb-configmap
        image: mongo-express
        imagePullPolicy: Always
        name: mongo-express
        ports:
        - containerPort: 8081
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-12-11T16:07:47Z"
    lastUpdateTime: "2024-12-11T16:17:29Z"
    message: ReplicaSet "mongo-express-85d8576d55" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-12-12T10:41:26Z"
    lastUpdateTime: "2024-12-12T10:41:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
